name: My First Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4


      - name: Welcome message
        run: echo "My first GitHub Actions Job"


      - name: List files and Read Files
        run: |
          echo "My first GitHub Actions job"
          ls -ltra
          cat README.md
